#!/usr/bin/env python3
import argparse

from mininet.cli import CLI
from mininet.link import TCLink
from mininet.log import info, setLogLevel
from mininet.net import Mininet

from p4_mininet import P4Host, P4Switch

DEFAULT_LINK_BW_MBPS = 10.0

def build_net(p4_json: str, sw_path: str, thrift_base: int, link_bw_mbps: float) -> Mininet:
    net = Mininet(controller=None, build=False, host=P4Host, link=TCLink, autoSetMacs=False)

    h1 = net.addHost("h1", ip="10.0.0.1/24", mac="00:00:00:00:01:01")
    h2 = net.addHost("h2", ip="10.0.0.2/24", mac="00:00:00:00:02:02")

    switches = {}
    for i in range(1, 6):
        switches[f's{i}'] = net.addSwitch(
            f's{i}',
            cls=P4Switch,
            sw_path=sw_path,
            json_path=p4_json,
            thrift_port=thrift_base + (i - 1),
            device_id=i,
        )

    # Topology Mesh
    # H1 - S1
    net.addLink(h1, switches['s1'], port1=0, port2=1, bw=link_bw_mbps)
    
    # S1 links (S2, S3)
    net.addLink(switches['s1'], switches['s2'], port1=2, port2=1, bw=link_bw_mbps)
    net.addLink(switches['s1'], switches['s3'], port1=3, port2=1, bw=link_bw_mbps)
    
    # S2 links (S4, S5)
    net.addLink(switches['s2'], switches['s4'], port1=2, port2=1, bw=link_bw_mbps)
    net.addLink(switches['s2'], switches['s5'], port1=3, port2=1, bw=link_bw_mbps)
    
    # S3 links (S4)
    net.addLink(switches['s3'], switches['s4'], port1=2, port2=2, bw=link_bw_mbps)
    
    # S4 links (S5)
    net.addLink(switches['s4'], switches['s5'], port1=3, port2=2, bw=link_bw_mbps)
    
    # S5 links (H2)
    net.addLink(switches['s5'], h2, port1=3, port2=0, bw=link_bw_mbps)

    net.build()
    
    for sw in switches.values():
        sw.start([])

    # Static ARP
    h1.cmd("arp -s 10.0.0.2 00:aa:00:00:02:02")
    h2.cmd("arp -s 10.0.0.1 00:aa:00:00:01:01")

    return net

def main() -> None:
    parser = argparse.ArgumentParser(description="Complex P4 topology with 5 switches")
    parser.add_argument("--json", required=True, help="Path to BMv2 JSON generated by p4c-bm2-ss")
    parser.add_argument("--switch-bin", default="simple_switch", help="Path to simple_switch binary")
    parser.add_argument("--thrift-base", type=int, default=9090, help="Thrift base port (S1=base)")
    parser.add_argument("--link-bw-mbps", type=float, default=DEFAULT_LINK_BW_MBPS, help="Bandwidth for each Mininet link in Mbps")
    parser.add_argument("--no-cli", action="store_true", help="Start topology, run quick ping test, then exit")
    args = parser.parse_args()

    net = build_net(args.json, args.switch_bin, args.thrift_base, args.link_bw_mbps)

    info("\nComplex Topology started. Next steps:\n")
    info("  1) bash network_simulation/program_complex.sh\n")
    info("  2) python3 telemetry_system/deploy_telemetry.py\n")

    if args.no_cli:
        net.pingAll(timeout=2)
        net.stop()
        return

    CLI(net)
    net.stop()

if __name__ == "__main__":
    setLogLevel("info")
    main()
