#!/usr/bin/env python3
import argparse

from mininet.cli import CLI
from mininet.link import TCLink
from mininet.log import info, setLogLevel
from mininet.net import Mininet

from p4_mininet import P4Host, P4Switch


DEFAULT_LINK_BW_MBPS = 10.0


def build_net(p4_json: str, sw_path: str, thrift_base: int, link_bw_mbps: float) -> Mininet:
    net = Mininet(controller=None, build=False, host=P4Host, link=TCLink, autoSetMacs=False)

    h1 = net.addHost("h1", ip="10.0.0.1/24", mac="00:00:00:00:01:01")
    h2 = net.addHost("h2", ip="10.0.0.2/24", mac="00:00:00:00:02:02")

    s1 = net.addSwitch(
        "s1",
        cls=P4Switch,
        sw_path=sw_path,
        json_path=p4_json,
        thrift_port=thrift_base,
        device_id=1,
    )
    s2 = net.addSwitch(
        "s2",
        cls=P4Switch,
        sw_path=sw_path,
        json_path=p4_json,
        thrift_port=thrift_base + 1,
        device_id=2,
    )

    net.addLink(h1, s1, port2=1, bw=link_bw_mbps)
    net.addLink(s1, s2, port1=2, port2=1, bw=link_bw_mbps)
    net.addLink(s2, h2, port1=2, bw=link_bw_mbps)

    net.build()
    s1.start([])
    s2.start([])

    # Static ARP avoids running ARP handling in the P4 data plane.
    h1.cmd("arp -s 10.0.0.2 00:aa:00:00:01:01")
    h2.cmd("arp -s 10.0.0.1 00:aa:00:00:02:02")

    return net


def main() -> None:
    parser = argparse.ArgumentParser(description="Linear P4 topology: H1-S1-S2-H2")
    parser.add_argument("--json", required=True, help="Path to BMv2 JSON generated by p4c-bm2-ss")
    parser.add_argument("--switch-bin", default="simple_switch", help="Path to simple_switch binary")
    parser.add_argument("--thrift-base", type=int, default=9090, help="Thrift base port (S1=base)")
    parser.add_argument(
        "--link-bw-mbps",
        type=float,
        default=DEFAULT_LINK_BW_MBPS,
        help="Bandwidth for each Mininet link in Mbps",
    )
    parser.add_argument(
        "--no-cli",
        action="store_true",
        help="Start topology, run quick ping test, then exit",
    )
    args = parser.parse_args()

    net = build_net(args.json, args.switch_bin, args.thrift_base, args.link_bw_mbps)

    info("\nTopology started. Next steps:\n")
    info("  1) ./control_plane/program_linear.sh\n")
    info("  2) h1 ping -c 3 10.0.0.2\n")
    info("  3) python3 control_plane/read_latency.py --thrift-port 9090 --indices 2\n\n")
    info(
        f"  4) python3 control_plane/read_transmission_delay.py --thrift-port 9090 --indices 2 --link-bw-mbps {args.link_bw_mbps}\n\n"
    )

    if args.no_cli:
        net.pingAll(timeout=2)
        net.stop()
        return

    CLI(net)
    net.stop()


if __name__ == "__main__":
    setLogLevel("info")
    main()
