#!/usr/bin/env python3
import argparse

from mininet.cli import CLI
from mininet.link import TCLink
from mininet.log import info, setLogLevel
from mininet.net import Mininet

from p4_mininet import P4Host, P4Switch


DEFAULT_PROBE_BW_MBPS = 1000.0
DEFAULT_BOTTLENECK_BW_MBPS = 10.0


def build_net(
    p4_json: str,
    sw_path: str,
    thrift_base: int,
    probe_bw_mbps: float,
    bottleneck_bw_mbps: float,
) -> Mininet:
    net = Mininet(controller=None, build=False, host=P4Host, link=TCLink, autoSetMacs=False)

    h1 = net.addHost("h1", ip="10.0.0.1/24", mac="00:00:00:00:01:01")
    h2 = net.addHost("h2", ip="10.0.0.2/24", mac="00:00:00:00:02:02")
    probe_s1 = net.addHost("probe_s1", ip="10.0.10.1/24", mac="00:00:00:00:0A:01")
    probe_s2 = net.addHost("probe_s2", ip="10.0.10.2/24", mac="00:00:00:00:0A:02")

    s1 = net.addSwitch(
        "s1",
        cls=P4Switch,
        sw_path=sw_path,
        json_path=p4_json,
        thrift_port=thrift_base,
        device_id=1,
    )
    s2 = net.addSwitch(
        "s2",
        cls=P4Switch,
        sw_path=sw_path,
        json_path=p4_json,
        thrift_port=thrift_base + 1,
        device_id=2,
    )

    # Port plan:
    # s1:1-h1, 2-s2, 3-probe_s1
    # s2:1-s1, 2-h2, 3-probe_s2
    net.addLink(h1, s1, port2=1, bw=probe_bw_mbps)
    net.addLink(s1, s2, port1=2, port2=1, bw=bottleneck_bw_mbps)
    net.addLink(s2, h2, port1=2, bw=probe_bw_mbps)
    net.addLink(probe_s1, s1, port1=1, port2=3, bw=probe_bw_mbps)
    net.addLink(probe_s2, s2, port1=1, port2=3, bw=probe_bw_mbps)

    net.build()
    s1.start([])
    s2.start([])

    # Static ARP keeps the existing IPv4 path usable without ARP handling in P4.
    h1.cmd("arp -s 10.0.0.2 00:aa:00:00:01:01")
    h2.cmd("arp -s 10.0.0.1 00:aa:00:00:02:02")

    return net


def main() -> None:
    parser = argparse.ArgumentParser(description="Packet-pair topology: H1-S1-S2-H2 with side probes")
    parser.add_argument("--json", required=True, help="Path to BMv2 JSON generated by p4c-bm2-ss")
    parser.add_argument("--switch-bin", default="simple_switch", help="Path to simple_switch binary")
    parser.add_argument("--thrift-base", type=int, default=9090, help="Thrift base port (S1=base)")
    parser.add_argument(
        "--probe-bw-mbps",
        type=float,
        default=DEFAULT_PROBE_BW_MBPS,
        help="Bandwidth used on probe host links in Mbps",
    )
    parser.add_argument(
        "--bottleneck-bw-mbps",
        type=float,
        default=DEFAULT_BOTTLENECK_BW_MBPS,
        help="Bandwidth used on the inter-switch bottleneck in Mbps",
    )
    parser.add_argument(
        "--no-cli",
        action="store_true",
        help="Start topology, run quick ping tests, then exit",
    )
    args = parser.parse_args()

    net = build_net(args.json, args.switch_bin, args.thrift_base, args.probe_bw_mbps, args.bottleneck_bw_mbps)

    info("\nTopology started. Next steps:\n")
    info("  1) ./control_plane/program_packet_pair.sh\n")
    info("  2) sudo python3 control_plane/sniff_probes.py --iface probe_s2-eth0\n")
    info("  3) sudo python3 control_plane/send_probes.py --iface probe_s1-eth0\n\n")
    info(f"  4) h1 ping -c 3 10.0.0.2   # optional regression check, probe links={args.probe_bw_mbps} Mbps\n\n")

    if args.no_cli:
        net.pingAll(timeout=2)
        net.stop()
        return

    CLI(net)
    net.stop()


if __name__ == "__main__":
    setLogLevel("info")
    main()
