#!/usr/bin/env python3
import argparse

from mininet.cli import CLI
from mininet.link import TCLink
from mininet.log import info, setLogLevel
from mininet.net import Mininet

from p4_mininet import P4Host, P4Switch


DEFAULT_LINK_BW_MBPS = 10.0


def build_net(p4_json: str, sw_path: str, thrift_base: int, link_bw_mbps: float) -> Mininet:
    net = Mininet(controller=None, build=False, host=P4Host, link=TCLink, autoSetMacs=False)

    h1 = net.addHost("h1", ip="10.0.0.1/24", mac="00:00:00:00:01:01")
    h2 = net.addHost("h2", ip="10.0.20.2/24", mac="00:00:00:00:02:02")

    s1 = net.addSwitch(
        "s1",
        cls=P4Switch,
        sw_path=sw_path,
        json_path=p4_json,
        thrift_port=thrift_base,
        device_id=1,
    )
    s2 = net.addSwitch(
        "s2",
        cls=P4Switch,
        sw_path=sw_path,
        json_path=p4_json,
        thrift_port=thrift_base + 1,
        device_id=2,
    )
    s3 = net.addSwitch(
        "s3",
        cls=P4Switch,
        sw_path=sw_path,
        json_path=p4_json,
        thrift_port=thrift_base + 2,
        device_id=3,
    )

    # Port plan:
    # s1:1-h1, 2-s2, 3-s3
    # s2:1-s1, 2-s3
    # s3:1-s1, 2-s2, 3-h2
    net.addLink(h1, s1, port2=1, bw=link_bw_mbps)
    net.addLink(s1, s2, port1=2, port2=1, bw=link_bw_mbps)
    net.addLink(s1, s3, port1=3, port2=1, bw=link_bw_mbps)
    net.addLink(s2, s3, port1=2, port2=2, bw=link_bw_mbps)
    net.addLink(s3, h2, port1=3, bw=link_bw_mbps)

    net.build()
    s1.start([])
    s2.start([])
    s3.start([])

    # Add a second destination class on H2 to trigger a second route on S1.
    h2.cmd("ip addr add 10.0.30.2/24 dev h2-eth0")

    # Static ARP + host routes avoid ARP logic in the P4 program.
    h1.cmd("ip route add 10.0.20.2/32 dev h1-eth0")
    h1.cmd("ip route add 10.0.30.2/32 dev h1-eth0")
    h1.cmd("arp -s 10.0.20.2 00:aa:00:00:01:01")
    h1.cmd("arp -s 10.0.30.2 00:aa:00:00:01:01")

    h2.cmd("ip route add 10.0.0.1/32 dev h2-eth0")
    h2.cmd("arp -s 10.0.0.1 00:aa:00:00:03:03")

    return net


def main() -> None:
    parser = argparse.ArgumentParser(description="Triangle P4 topology with two probe neighbors from S1")
    parser.add_argument("--json", required=True, help="Path to BMv2 JSON generated by p4c-bm2-ss")
    parser.add_argument("--switch-bin", default="simple_switch", help="Path to simple_switch binary")
    parser.add_argument("--thrift-base", type=int, default=9090, help="Thrift base port (S1=base)")
    parser.add_argument(
        "--link-bw-mbps",
        type=float,
        default=DEFAULT_LINK_BW_MBPS,
        help="Bandwidth for each Mininet link in Mbps",
    )
    parser.add_argument(
        "--no-cli",
        action="store_true",
        help="Start topology, run quick ping tests, then exit",
    )
    args = parser.parse_args()

    net = build_net(args.json, args.switch_bin, args.thrift_base, args.link_bw_mbps)

    info("\nTopology started. Next steps:\n")
    info("  1) ./control_plane/program_triangle.sh\n")
    info("  2) h1 ping -c 3 10.0.20.2\n")
    info("  3) h1 ping -c 3 10.0.30.2\n")
    info("  4) python3 control_plane/read_latency.py --thrift-port 9090 --indices 2,3\n\n")
    info(
        f"  5) python3 control_plane/read_transmission_delay.py --thrift-port 9090 --indices 2,3 --link-bw-mbps {args.link_bw_mbps}\n\n"
    )

    if args.no_cli:
        h1 = net.get("h1")
        h1.cmd("ping -c 2 10.0.20.2")
        h1.cmd("ping -c 2 10.0.30.2")
        net.stop()
        return

    CLI(net)
    net.stop()


if __name__ == "__main__":
    setLogLevel("info")
    main()
