#!/usr/bin/env bash
# Procedimento manual End-to-End para o Ecossistema SDN
# Use este script como referÃªncia (ou execute-o diretamente para ler as instruÃ§Ãµes)

echo "=== DocumentaÃ§Ã£o de Teste End-to-End do SDN Telemetry ==="
echo "Para testar o ecossistema completo (Data Plane + Control Plane), siga os passos abaixo"
echo "abrindo terminais separados no seu ambiente Linux (ex: VM Ubuntu com BMv2):"
echo ""

echo "---------------------------------------------------"
echo "[Terminal 1] 1. Compilar P4 e Iniciar Mininet"
echo "---------------------------------------------------"
echo "Navegue atÃ© a raiz do projeto e execute:"
echo "   make clean"
echo "   sudo python3 topologies/linear_topo.py"
echo "(Deixe este terminal rodando. O prompt do mininet ficarÃ¡ aberto)"
echo ""

echo "---------------------------------------------------"
echo "[Terminal 2] 2. Programar switches via Thrift"
echo "---------------------------------------------------"
echo "Abra outro terminal na raiz do projeto e aplique as regras P4 e registradores:"
echo "   ./control_plane/program_linear.sh"
echo "(VocÃª verÃ¡ a confirmaÃ§Ã£o '[OK] s1 programmed' e '[OK] s2 programmed')"
echo ""

echo "---------------------------------------------------"
echo "[Terminal 3] 3. Iniciar a CLI e Coletor UDP"
echo "---------------------------------------------------"
echo "Abra um terceiro terminal e inicie o CÃ©rebro do sistema:"
echo "   python3 control_plane/cli.py --topo linear_test"
echo "(VocÃª verÃ¡ o prompt 'sdn>' indicando que o controlador estÃ¡ escutando na porta 9999)"
echo ""

echo "---------------------------------------------------"
echo "[Terminal 1 - Mininet] 4. Gerar TrÃ¡fego"
echo "---------------------------------------------------"
echo "Volte para o terminal do mininet e force a geraÃ§Ã£o de sondas enviando trÃ¡fego real:"
echo "   mininet> pingall"
echo "   mininet> h1 ping h2 -c 10"
echo "Nesse momento, o Data Plane comeÃ§arÃ¡ a clonar sondas UDP para o Coletor."
echo ""

echo "---------------------------------------------------"
echo "[Terminal 3 - CLI SDN] 5. Interagir com a Rede"
echo "---------------------------------------------------"
echo "Volte para a CLI (sdn>) e use a inteligÃªncia do sistema:"
echo ""
echo "a) Inferir e mostrar topologia:"
echo "   sdn> topology infer"
echo "   sdn> topology show"
echo "   (Os enlaces fÃ­sicos com mÃ©tricas de latÃªncia devem aparecer)"
echo ""
echo "b) Criar um Snapshot (foto) do estado da rede:"
echo "   sdn> snapshot create"
echo "   sdn> snapshot show 1"
echo ""
echo "c) Ajustar a frequÃªncia dinamicamente:"
echo "   sdn> show frequency 1 2"
echo "   sdn> set frequency 1 2 500"
echo "   (O switch passarÃ¡ a enviar sondas a cada 500ms)"
echo ""
echo "d) Ligar/Desligar sondas individualmente:"
echo "   sdn> metric list 1"
echo "   sdn> metric disable 1 <handle_id>"
echo ""

echo "Fim do Teste. ParabÃ©ns, seu ecossistema SDN autÃ´nomo estÃ¡ pronto!"
