#!/usr/bin/env bash
# Procedimento manual End-to-End para o Ecossistema SDN
# Use este script como referência (ou execute-o diretamente para ler as instruções)

echo "=== Documentação de Teste End-to-End do SDN Telemetry ==="
echo "Para testar o ecossistema completo (Data Plane + Control Plane), siga os passos abaixo"
echo "abrindo terminais separados no seu ambiente Linux (ex: VM Ubuntu com BMv2):"
echo ""

echo "---------------------------------------------------"
echo "[Terminal 1] 1. Compilar P4 e Iniciar Mininet"
echo "---------------------------------------------------"
echo "Navegue até a raiz do projeto e execute:"
echo "   make clean"
echo "   sudo python3 topologies/linear_topo.py"
echo "(Deixe este terminal rodando. O prompt do mininet ficará aberto)"
echo ""

echo "---------------------------------------------------"
echo "[Terminal 2] 2. Programar switches via Thrift"
echo "---------------------------------------------------"
echo "Abra outro terminal na raiz do projeto e aplique as regras P4 e registradores:"
echo "   ./control_plane/program_linear.sh"
echo "(Você verá a confirmação '[OK] s1 programmed' e '[OK] s2 programmed')"
echo ""

echo "---------------------------------------------------"
echo "[Terminal 3] 3. Iniciar a CLI e Coletor UDP"
echo "---------------------------------------------------"
echo "Abra um terceiro terminal e inicie o Cérebro do sistema:"
echo "   python3 control_plane/cli.py --topo linear_test"
echo "(Você verá o prompt 'sdn>' indicando que o controlador está escutando na porta 9999)"
echo ""

echo "---------------------------------------------------"
echo "[Terminal 1 - Mininet] 4. Gerar Tráfego"
echo "---------------------------------------------------"
echo "Volte para o terminal do mininet e force a geração de sondas enviando tráfego real:"
echo "   mininet> pingall"
echo "   mininet> h1 ping h2 -c 10"
echo "Nesse momento, o Data Plane começará a clonar sondas UDP para o Coletor."
echo ""

echo "---------------------------------------------------"
echo "[Terminal 3 - CLI SDN] 5. Interagir com a Rede"
echo "---------------------------------------------------"
echo "Volte para a CLI (sdn>) e use a inteligência do sistema:"
echo ""
echo "a) Inferir e mostrar topologia:"
echo "   sdn> topology infer"
echo "   sdn> topology show"
echo "   (Os enlaces físicos com métricas de latência devem aparecer)"
echo ""
echo "b) Criar um Snapshot (foto) do estado da rede:"
echo "   sdn> snapshot create"
echo "   sdn> snapshot show 1"
echo ""
echo "c) Ajustar a frequência dinamicamente:"
echo "   sdn> show frequency 1 2"
echo "   sdn> set frequency 1 2 500"
echo "   (O switch passará a enviar sondas a cada 500ms)"
echo ""
echo "d) Ligar/Desligar sondas individualmente:"
echo "   sdn> metric list 1"
echo "   sdn> metric disable 1 <handle_id>"
echo ""

echo "Fim do Teste. Parabéns, seu ecossistema SDN autônomo está pronto!"
